### ISSUE TITLE
getting this error on Garuda Linux

### ISSUE THREAD

**Issue by HeikoLinux** [stele95/LinVAM#48]
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/linvam/commandeditwnd.py", line 107, in slot_new_sound_edit
w_sound_edit_wnd = SoundActionEditWnd(self.m_parent.m_parent.m_sound, None, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWnd' object has no attribute 'm_sound'
fish: Job 1, 'linvam --debug' terminated by signal SIGABRT (Abbruch)

**Comment by stele95** [comment]
Try now with the latest commit

**Comment by HeikoLinux** [comment]
nice it is working now. This was realy fast Thank you!
